scrape_configs:
    - job_name: 'apps'
      scrape_interval: 10s
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['host.docker.internal:8082','host.docker.internal:8083']
